#!/bin/bash
#
export NOCOLOR='\033[0m'
export GREEN='\033[0;32m'
export CYAN='\033[0;36m'
export YELLOW='\033[1;32m'
export MAGENTA='\033[0;35m'
export RED='\033[0;31m'

protected_branch='main'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

### Check versions
#
REPO_ROOT_PATH=$(git rev-parse --show-toplevel)
changelog_version=$(egrep '## [0-9]\d*(\.[0-9]\d*)*$' $REPO_ROOT_PATH/tesla_ble_mqtt/CHANGELOG.md | head -1 | cut -d ' ' -f2)
addon_config_version=$(grep ^version $REPO_ROOT_PATH/tesla_ble_mqtt/config.yaml|awk -F\" '{print $2}')
mqtt_software_version=$(grep \"sw_version\" $REPO_ROOT_PATH/tesla_ble_mqtt/rootfs/app/discovery.sh|awk -F\" '{print $4}')

if [ "$changelog_version" != "$addon_config_version" \
  -o "$changelog_version" != "$mqtt_software_version" ]; then
  echo "Please adjust versions to be identical:"
  echo "changelog_version    : $changelog_version"
  echo "addon_config_version : $addon_config_version"
  echo "mqtt_software_version: $mqtt_software_version"

  echo 'If you still want to proceed add "--no-verify" to your git push'
  exit 1
fi
### END Check versions


### Check if branch is protected
#

if [ $protected_branch = $current_branch ]; then
  echo -e "${RED}ATTENTION:$NOCOLOR You are on protected ${RED}branch $protected_branch${NOCOLOR}"
  read -p "Are you sure you want to push here? (yes/no) " -n 3 -r </dev/tty
  echo
  if echo $REPLY | grep -E '^[Yy][Ee][Ss]$' >/dev/null; then
    exit 0 # push will execute
  fi
  exit 1 # push will not execute
else
  exit 0 # push will execute
fi
